# 阶段一：文生图评估系统配置

# 数据集配置
datasets:
  parti_prompts:
    name: "nateraw/parti-prompts"
    local_path: "data/parti_prompts"
    download: true
  
  t2i_factualbench:
    name: "Sakeoffellow001/T2i_Factualbench"
    local_path: "data/t2i_factualbench"
    download: true

  t2i_compbench:
    name: "NinaKarine/t2i-compbench"
    local_path: "data/t2i_compbench"
    download: true

# 评估指标配置
metrics:
  clip_score:
    model_name: "openai/clip-vit-base-patch32"
    enabled: true
  
  image_reward:
    model_name: "THUDM/ImageReward"
    enabled: true
  
  pick_score:
    model_name: "yuvalkirstain/PickScore_v1"
    enabled: true
  
  tifa:
    model_name: "microsoft/unilm-base-cased"
    enabled: true
  
  fid:
    batch_size: 50
    dims: 2048
    enabled: true
  
  inception_score:
    batch_size: 32
    splits: 10
    enabled: true

# 评估配置
evaluation:
  batch_size: 8  # 减少以适应服务器内存限制
  num_workers: 2  # 减少以适应服务器环境
  device: "auto"  # auto, cuda, cpu - 自动检测最佳设备
  output_dir: "results/stage1"
  save_detailed_results: true

# 模型缓存配置
cache:
  model_cache_dir: "models/cache"
  feature_cache_dir: "results/cache"
  use_cache: true
