# 阶段三：创新幻觉缓解方案配置

# 强化学习对齐方法配置
reinforcement_learning:
  # 环境配置
  environment:
    name: "text_image_alignment"
    max_steps: 100
    reward_threshold: 0.8
  
  # 智能体配置
  agent:
    algorithm: "PPO"  # PPO, A2C, SAC
    policy_network:
      hidden_dims: [256, 128]
      activation: "relu"
    value_network:
      hidden_dims: [256, 128]
      activation: "relu"
  
  # 训练配置
  training:
    total_timesteps: 100000
    learning_rate: 3e-4
    batch_size: 64
    n_steps: 2048
    n_epochs: 10
    gamma: 0.99
    gae_lambda: 0.95
    clip_range: 0.2
    ent_coef: 0.01
    vf_coef: 0.5
  
  # 奖励函数配置
  reward:
    # 语义一致性奖励权重
    semantic_consistency_weight: 0.4
    # 细节准确性奖励权重
    detail_accuracy_weight: 0.3
    # 整体质量奖励权重
    overall_quality_weight: 0.3
    # 惩罚系数
    hallucination_penalty: -1.0

# 多模态检索增强配置
retrieval_augmentation:
  # 知识库配置
  knowledge_base:
    type: "vector_db"  # vector_db, graph_db
    embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
    vector_dim: 384
    index_type: "faiss"  # faiss, chromadb
    
  # 检索配置
  retrieval:
    top_k: 5
    similarity_threshold: 0.7
    rerank: true
    rerank_model: "cross-encoder/ms-marco-MiniLM-L-6-v2"
  
  # 知识源配置
  knowledge_sources:
    - name: "wikipedia"
      type: "text"
      path: "data/knowledge/wikipedia"
      enabled: true
    - name: "conceptnet"
      type: "graph"
      path: "data/knowledge/conceptnet"
      enabled: true
    - name: "visual_genome"
      type: "visual"
      path: "data/knowledge/visual_genome"
      enabled: false
  
  # 增强策略配置
  augmentation:
    method: "context_injection"  # context_injection, prompt_rewriting
    max_context_length: 512
    context_weight: 0.3

# 幻觉检测与定位配置
hallucination_detection:
  # 检测模型配置
  detection_model:
    model_path: "models/stage2/best_model.pth"
    confidence_threshold: 0.5
  
  # 定位方法配置
  localization:
    method: "attention_maps"  # attention_maps, grad_cam, lime
    granularity: "region"  # pixel, region, object
    
  # 可解释性配置
  explainability:
    generate_heatmaps: true
    generate_text_attribution: true
    save_visualizations: true

# 集成系统配置
integrated_system:
  # 流水线配置
  pipeline:
    stages:
      - "detection"      # 幻觉检测
      - "localization"   # 幻觉定位
      - "retrieval"      # 知识检索
      - "correction"     # 幻觉纠正
      - "validation"     # 结果验证
  
  # 纠正策略配置
  correction:
    method: "iterative"  # iterative, one_shot
    max_iterations: 3
    improvement_threshold: 0.1
  
  # 验证配置
  validation:
    use_multiple_metrics: true
    metrics: ["clip_score", "tifa", "detection_confidence"]
    consensus_threshold: 0.7

# 实验配置
experiments:
  # 数据集配置
  datasets:
    test_sets:
      - "parti_prompts_subset"
      - "t2i_factualbench_subset"
      - "custom_hallucination_cases"
    
    sample_sizes:
      small: 50
      medium: 200
      large: 500
  
  # 基线方法配置
  baselines:
    - name: "no_correction"
      description: "原始生成结果，无纠正"
    - name: "simple_filtering"
      description: "基于置信度的简单过滤"
    - name: "prompt_engineering"
      description: "改进提示词工程"
  
  # 评估指标配置
  evaluation_metrics:
    - "hallucination_detection_accuracy"
    - "hallucination_localization_iou"
    - "correction_effectiveness"
    - "semantic_preservation"
    - "visual_quality"

# 输出配置
output:
  results_dir: "results/stage3"
  models_dir: "models/stage3"
  visualizations_dir: "results/stage3/visualizations"
  logs_dir: "logs/stage3"

# 设备和性能配置
device: "cuda"
num_workers: 4
batch_size: 16
mixed_precision: true
